# Generated by Django 5.1.15 on 2026-09-22 10:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='paid', max_length=16)),
                ('total_paise', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField()),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('line1', models.TextField()),
                ('line2', models.TextField(blank=True, null=True)),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pincode', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'shipping addresses',
                'db_table': 'shipping_addresses',
            },
        ),
        migrations.CreateModel(
            name='ShippingQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField()),
                ('pincode', models.TextField()),
                ('weight_grams', models.IntegerField()),
                ('amount_paise', models.IntegerField()),
                ('courier', models.TextField(blank=True, null=True)),
                ('etd_days', models.SmallIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shipping_quotes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('sort', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'shop_categories',
                'ordering': ('sort', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('order', models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='shipment', serialize=False, to='shop.order')),
                ('address', models.JSONField()),
                ('pincode', models.TextField()),
                ('weight_grams', models.IntegerField()),
                ('shipping_paise', models.IntegerField()),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('ready', 'Ready'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=24)),
                ('courier', models.TextField(blank=True, null=True)),
                ('awb', models.TextField(blank=True, null=True)),
                ('provider_order_id', models.TextField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.TextField()),
                ('item_id', models.UUIDField()),
                ('title', models.TextField()),
                ('qty', models.SmallIntegerField(default=1)),
                ('unit_price_paise', models.IntegerField()),
                ('tax_rate_bps', models.SmallIntegerField(default=0)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='shop.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='ShopSubcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('sort', models.SmallIntegerField(default=0)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategories', to='shop.shopcategory')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
                'db_table': 'shop_subcategories',
                'ordering': ('sort', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legacy_id', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('price_paise', models.IntegerField()),
                ('mrp_paise', models.IntegerField(blank=True, null=True)),
                ('tax_rate_bps', models.SmallIntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('weight_grams', models.IntegerField()),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='shop.shopcategory')),
                ('subcategory', models.ForeignKey(blank=True, db_column='subcategory_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='shop.shopsubcategory')),
            ],
            options={
                'db_table': 'products',
                'ordering': ('-featured', 'name'),
            },
        ),
    ]
