# Generated by Django 5.1.15 on 2026-09-22 10:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_existing_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('percent', 'Percentage off'), ('flat', 'Flat amount off')], max_length=8)),
                ('percent_off', models.SmallIntegerField(blank=True, null=True)),
                ('flat_off_paise', models.IntegerField(blank=True, null=True)),
                ('max_discount_paise', models.IntegerField(blank=True, null=True)),
                ('min_order_paise', models.IntegerField(default=0)),
                ('max_redemptions', models.IntegerField(blank=True, null=True)),
                ('used_count', models.IntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('flat_off_paise__isnull', True), ('kind', 'percent'), ('percent_off__isnull', False)), models.Q(('flat_off_paise__isnull', False), ('kind', 'flat'), ('percent_off__isnull', True)), _connector='OR'), name='coupon_one_shape_only'), models.CheckConstraint(condition=models.Q(('percent_off__isnull', True), models.Q(('percent_off__gt', 0), ('percent_off__lte', 100)), _connector='OR'), name='coupon_percent_in_range')],
            },
        ),
    ]
