# Generated by Django 5.1.15 on 2026-09-19 10:23
#
# ── FAKE IN AT CUTOVER — DO NOT RUN FOR REAL ON THE PRODUCTION DATABASE ──────
# This migration records Django's ownership of tables that ALREADY EXIST.
# `content`, `reviews` and `feed_pins` were created by
# backend/schema/020_content_reviews.sql, as amended by
# 025_seekers_publish.sql (which renamed content.consultant_id to author_id
# and repointed the key at profiles(id)); every constraint and index name
# below is the name Postgres already carries, nothing here creates anything
# new. At cutover: deploy the API against the existing database, then
# `manage.py migrate --fake-initial` (falls back to `--fake content` if
# inspectdb-level drift makes --fake-initial refuse). It runs for real only
# on fresh databases (tests, dev scratches).
# ─────────────────────────────────────────────────────────────────────────────

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('post', 'Post'), ('article', 'Article'), ('clip', 'Clip'), ('live_session', 'Live session')], max_length=16)),
                ('title', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('removed', 'Removed'), ('draft', 'Draft')], default='live', max_length=16)),
                ('view_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('legacy_id', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'content',
                'indexes': [models.Index(condition=models.Q(('status', 'live')), fields=['author_id', '-published_at'], name='content_author_idx'), models.Index(condition=models.Q(('status', 'live')), fields=['-published_at'], name='content_published_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['post', 'article', 'clip', 'live_session'])), name='content_kind_check'), models.CheckConstraint(condition=models.Q(('status__in', ['live', 'removed', 'draft'])), name='content_status_check'), models.CheckConstraint(condition=models.Q(('view_count__gte', 0)), name='content_view_count_check')],
            },
        ),
        migrations.CreateModel(
            name='FeedPin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('ref_id', models.UUIDField()),
                ('sort', models.SmallIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'feed_pins',
                'indexes': [models.Index(fields=['sort', 'starts_at', 'ends_at'], name='feed_pins_window_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('starts_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='feed_pins_window_check')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('seeker_id', models.UUIDField()),
                ('consultant_id', models.UUIDField()),
                ('rating', models.SmallIntegerField()),
                ('body', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('removed', 'Removed')], default='live', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reviews',
                'indexes': [models.Index(condition=models.Q(('status', 'live')), fields=['consultant_id', '-created_at'], name='reviews_consultant_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='reviews_rating_check'), models.CheckConstraint(condition=models.Q(('status__in', ['live', 'removed'])), name='reviews_status_check')],
            },
        ),
    ]
