# Generated by Django 5.1.15 on 2026-09-23 14:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_id', models.UUIDField()),
                ('reporter_id', models.UUIDField()),
                ('reason', models.CharField(choices=[('spam', 'Spam or a scam'), ('abuse', 'Abuse, threats or harassment'), ('adult', 'Nudity or sexual content'), ('false', 'Dangerous or false claims'), ('other', 'Something else')], max_length=16)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open — nobody has looked'), ('upheld', 'Upheld — the post or the person was actioned'), ('dismissed', 'Dismissed — nothing wrong with it')], default='open', max_length=16)),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.ForeignKey(blank=True, db_column='content_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='content.content')),
            ],
            options={
                'db_table': 'content_reports',
                'indexes': [models.Index(condition=models.Q(('status', 'open')), fields=['created_at'], name='content_reports_open_idx'), models.Index(fields=['subject_id', '-created_at'], name='content_reports_subject_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reason__in', ['spam', 'abuse', 'adult', 'false', 'other'])), name='content_reports_reason_check'), models.CheckConstraint(condition=models.Q(('status__in', ['open', 'upheld', 'dismissed'])), name='content_reports_status_check'), models.CheckConstraint(condition=models.Q(('reporter_id', models.F('subject_id')), _negated=True), name='content_reports_not_self_check'), models.UniqueConstraint(condition=models.Q(('content__isnull', False)), fields=('content', 'reporter_id'), name='content_reports_one_per_post'), models.UniqueConstraint(condition=models.Q(('content__isnull', True)), fields=('subject_id', 'reporter_id'), name='content_reports_one_per_person')],
            },
        ),
    ]
