# Generated by Django 5.1.15 on 2026-09-30 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


def close_to_postgrest(apps, schema_editor):
    """RLS on, no policies. Supabase grants anon and authenticated on every
    new table in `public`, so without this the table would be readable and
    writable straight through the PostgREST API with the anon key that ships
    in the app. Django connects as the table owner, which RLS does not bind,
    so the API is unaffected. Postgres only — the test suite runs on SQLite."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("alter table content_products enable row level security")


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_report'),
        ('shop', '0002_coupons'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort', models.SmallIntegerField(default=0)),
                ('content', models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='content.content')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_tags', to='shop.product')),
            ],
            options={
                'db_table': 'content_products',
                'ordering': ('sort',),
                'constraints': [models.UniqueConstraint(fields=('content', 'product'), name='content_products_once')],
            },
        ),
        migrations.RunPython(close_to_postgrest, migrations.RunPython.noop),
    ]
