# Generated by Django 5.1.15 on 2026-09-30 15:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def close_to_postgrest(apps, schema_editor):
    """RLS on, no policies — the reason is in 0003_content_products."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("alter table content_views enable row level security")


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewer_id', models.UUIDField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='content.content')),
            ],
            options={
                'db_table': 'content_views',
                'constraints': [models.UniqueConstraint(fields=('content', 'viewer_id'), name='content_views_once')],
            },
        ),
        migrations.RunPython(close_to_postgrest, migrations.RunPython.noop),
    ]
