# Generated by Django 5.1.15 on 2026-09-30 17:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def close_to_postgrest(apps, schema_editor):
    """RLS on, no policies — the reason is in 0003_content_products."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("alter table content_comments enable row level security")


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_id', models.UUIDField()),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('live', 'Live'), ('removed', 'Removed')], default='live', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.content')),
            ],
            options={
                'db_table': 'content_comments',
                'indexes': [models.Index(condition=models.Q(('status', 'live')), fields=['content', 'created_at'], name='content_comments_thread_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['live', 'removed'])), name='content_comments_status_check')],
            },
        ),
        migrations.RunPython(close_to_postgrest, migrations.RunPython.noop),
    ]
