# Generated by Django 5.1.15 on 2026-09-21 11:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('profile_id', models.UUIDField(primary_key=True, serialize=False)),
                ('welcome_used', models.IntegerField(default=0)),
                ('last_free_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_quota',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField()),
                ('rate_paise', models.IntegerField()),
                ('status', models.CharField(choices=[('live', 'Live'), ('ended', 'Ended')], default='live', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('hold_paise', models.IntegerField()),
                ('charged_paise', models.IntegerField(blank=True, null=True)),
                ('order_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_sessions',
                'indexes': [models.Index(fields=['profile_id', '-started_at'], name='ai_sessions_mine_idx'), models.Index(fields=['status', 'expires_at'], name='ai_sessions_sweep_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField()),
                ('role', models.CharField(choices=[('user', 'User'), ('model', 'Model')], max_length=8)),
                ('body', models.TextField()),
                ('tokens_in', models.IntegerField(blank=True, null=True)),
                ('tokens_out', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='ai.session')),
            ],
            options={
                'db_table': 'ai_messages',
                'indexes': [models.Index(fields=['profile_id', 'created_at'], name='ai_messages_mine_idx'), models.Index(fields=['created_at'], name='ai_messages_age_idx')],
            },
        ),
    ]
