# Generated by Django 5.1.15 on 2026-09-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='daily_used',
            field=models.IntegerField(default=0),
        ),
    ]
