# Generated by Django 5.1.15 on 2026-09-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_quota_daily_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='bonus_daily',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quota',
            name='bonus_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
