# Generated by Django 5.1.15 on 2026-09-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Renumbered from 0003 on 25 Sep: the referral bonus took that
        # number on main first, and two 0003s on one app is a conflict
        # Django refuses to resolve on its own.
        ('ai', '0003_quota_bonus_daily_quota_bonus_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='tarot_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quota',
            name='tarot_week',
            field=models.DateField(blank=True, null=True),
        ),
    ]
