# Generated by Django 5.1.15 on 2026-09-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_quota_tarot_used_quota_tarot_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='bonus_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
