# Generated by Django 5.1.15 on 2026-09-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_quota_bonus_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='bonus_days',
            field=models.IntegerField(default=0),
        ),
    ]
