# Generated by Django 5.1.15 on 2026-09-19 08:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('reel', 'Reel'), ('image', 'Image'), ('audio', 'Audio')], max_length=16)),
                ('bucket_key', models.CharField(max_length=1024)),
                ('mime', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing'), ('failed', 'Failed')], default='processing', max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'media_assets',
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['reel', 'image', 'audio'])), name='media_kind_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['ready', 'processing', 'failed'])), name='media_status_valid'), models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='media_size_nonneg')],
            },
        ),
    ]
