# Generated by Django 5.1.15 on 2026-09-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mediaasset',
            name='media_kind_valid',
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='kind',
            field=models.CharField(choices=[('reel', 'Reel'), ('image', 'Image'), ('audio', 'Audio'), ('document', 'Document')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['reel', 'image', 'audio', 'document'])), name='media_kind_valid'),
        ),
    ]
