# Generated by Django 5.1.15 on 2026-09-19 17:02
# -- FAKE IN AT CUTOVER -- DO NOT RUN FOR REAL ON THE PRODUCTION DATABASE ----
# This migration records Django's ownership of a table that ALREADY EXISTS.
# `profiles` was created by the numbered SQL files — 001_profiles.sql (the
# identity spine: own-row-only RLS, handle_new_user makes the row at signup),
# 002_profiles_email.sql (the nullable contact column and its named shape
# CHECK, profiles_email_shape) and 027_profile_avatars.sql (avatar_url plus
# the re-issued column grant) — and every constraint name below is the name
# Postgres already carries, nothing here creates anything new on the real
# database. At cutover: deploy the API against the existing database, then
# `manage.py migrate --fake-initial` (falls back to `--fake profiles` if
# inspectdb-level drift makes --fake-initial refuse). It runs for real only
# on fresh databases (tests, dev scratches).
#
# Cross-module notes: `id` is the Supabase auth user id, a bare UUIDField
# with no local FK — identity stays in Supabase Auth (docs/07 §1) and
# handle_new_user's row creation STAYS a prod trigger after the fake-in;
# `apps.profiles.services.ensure_profile` is the same insert as code, for
# the window before the trigger fires and for fresh databases, and never
# double-writes what the trigger already did. Modules 3/5/6/7 read this
# table through apps.profiles.services now (module 9 re-pointed their raw
# gateways); nothing else issues SQL against `profiles`.
# -----------------------------------------------------------------------------

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('phone', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_time_known', models.BooleanField(default=False)),
                ('birth_place', models.TextField(blank=True, null=True)),
                ('birth_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('birth_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('birth_zone', models.TextField(blank=True, null=True)),
                ('admin', models.BooleanField(default=False)),
                ('legacy_id', models.TextField(blank=True, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'profiles',
                'constraints': [models.CheckConstraint(condition=models.Q(('email__iregex', '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$'), ('email__isnull', True), _connector='OR'), name='profiles_email_shape')],
            },
        ),
    ]
