# Generated by Django 5.1.15 on 2026-09-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_blocked_at_profile_blocked_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('gender__in', ('male', 'female', 'other')), ('gender__isnull', True), _connector='OR'), name='profiles_gender_check'),
        ),
    ]
