# Generated by Django 5.1.15 on 2026-10-03 18:17

from django.db import migrations, models


def keep_database_default(apps, schema_editor):
    """AddField drops the database default after adding the column, and
    `handle_new_user` inserts only (id, phone, name) — so without this every
    sign-up fails with "Database error saving new user", exactly as
    `video_enabled` did on 26 Sep (backend/schema/032)."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("alter table profiles alter column influencer set default false")


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='influencer',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(keep_database_default, migrations.RunPython.noop),
    ]
