# Generated by Django 5.1.15 on 2026-10-04 07:39

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


def close_to_postgrest(apps, schema_editor):
    """RLS on, no policies: read through the API only, like every table."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("alter table banners enable row level security")
    schema_editor.execute("alter table themes enable row level security")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='For the console only, e.g. Diwali 2026.', max_length=60)),
                ('accent', models.CharField(default='#f5782c', help_text='Replaces the saffron: tabs, highlights, the orange buttons. Usual: #f5782c', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'A colour like #c2410c.')])),
                ('button', models.CharField(default='#45bd82', help_text='Replaces the green main-action buttons. Usual: #45bd82', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'A colour like #c2410c.')])),
                ('greeting', models.CharField(blank=True, default='', help_text='Optional strip under the top bar, e.g. Shubh Deepavali', max_length=80)),
                ('greeting_hi', models.CharField(blank=True, default='', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'themes',
                'ordering': ('-starts_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placement', models.CharField(choices=[('consult', 'Consult'), ('shop', 'Shop'), ('bhakti', 'Bhakti')], max_length=16)),
                ('kicker', models.CharField(blank=True, default='', help_text='Small caps line on top, e.g. NEW or DIWALI', max_length=40)),
                ('title', models.CharField(max_length=80)),
                ('note', models.CharField(blank=True, default='', max_length=140)),
                ('cta', models.CharField(default='Open', max_length=30, verbose_name='Button text')),
                ('kicker_hi', models.CharField(blank=True, default='', max_length=40)),
                ('title_hi', models.CharField(blank=True, default='', max_length=80)),
                ('note_hi', models.CharField(blank=True, default='', max_length=140)),
                ('cta_hi', models.CharField(blank=True, default='', max_length=30)),
                ('link', models.CharField(blank=True, default='', help_text='Where a tap goes: an app path like /shop or /muhurat, or a full https:// address. Empty: not tappable.', max_length=300)),
                ('colour_from', models.CharField(default='#7c2d12', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'A colour like #c2410c.')])),
                ('colour_to', models.CharField(default='#c2410c', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'A colour like #c2410c.')])),
                ('image_url', models.TextField(blank=True, default='', help_text='Optional picture behind the text.')),
                ('sort', models.SmallIntegerField(default=0, help_text='Lower comes first.')),
                ('replace_defaults', models.BooleanField(default=False, help_text="Hide this screen's built-in banners while this one is showing.")),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'banners',
                'ordering': ('placement', 'sort', '-created_at'),
                'constraints': [models.CheckConstraint(condition=models.Q(('placement__in', ['consult', 'shop', 'bhakti'])), name='banners_placement_valid')],
            },
        ),
        migrations.RunPython(close_to_postgrest, migrations.RunPython.noop),
    ]
