# Generated by Django 5.1.15 on 2026-09-19 10:05
#
# ── FAKE IN AT CUTOVER — DO NOT RUN FOR REAL ON THE PRODUCTION DATABASE ──────
# This migration records Django's ownership of a table that ALREADY EXISTS.
# `bhakti_assets` was created by backend/schema/024_bhakti_assets.sql and
# amended by 026_bhakti_status_kind.sql (which merged 'ringtone' into 'tune'
# and added the leading 'status' kind, re-creating bhakti_assets_kind_check);
# every constraint and index name below is the name Postgres already carries,
# nothing here creates anything new. At cutover: deploy the API against the
# existing database, then `manage.py migrate --fake-initial` (falls back to
# `--fake bhakti` if inspectdb-level drift makes --fake-initial refuse).
# It runs for real only on fresh databases (tests, dev scratches).
# ─────────────────────────────────────────────────────────────────────────────

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BhaktiAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('status', 'Status'), ('wallpaper', 'Wallpaper'), ('tune', 'Tune'), ('bhajan', 'Bhajan')], max_length=16)),
                ('title', models.TextField()),
                ('deity', models.TextField(blank=True, null=True)),
                ('media_url', models.TextField()),
                ('preview_url', models.TextField(blank=True, null=True)),
                ('price_paise', models.IntegerField(blank=True, null=True)),
                ('artist', models.TextField()),
                ('licence', models.TextField()),
                ('source', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
                ('legacy_id', models.TextField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bhakti_assets',
                'indexes': [models.Index(condition=models.Q(('active', True)), fields=['kind', 'sort'], name='bhakti_assets_kind_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['status', 'wallpaper', 'tune', 'bhajan'])), name='bhakti_assets_kind_check'), models.CheckConstraint(condition=models.Q(('title__regex', '\\S')), name='bhakti_assets_title_check'), models.CheckConstraint(condition=models.Q(('price_paise__isnull', True), ('price_paise__gt', 0), _connector='OR'), name='bhakti_assets_price_paise_check')],
            },
        ),
    ]
