# Generated by Django 5.1.15 on 2026-09-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhakti', '0002_ebook_kind'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bhaktiasset',
            name='bhakti_assets_kind_check',
        ),
        migrations.AlterField(
            model_name='bhaktiasset',
            name='kind',
            field=models.CharField(choices=[('status', 'Status'), ('wallpaper', 'Wallpaper'), ('tune', 'Tune'), ('bhajan', 'Bhajan'), ('ebook', 'E-book'), ('mantra', 'Mantra')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='bhaktiasset',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['status', 'wallpaper', 'tune', 'bhajan', 'ebook', 'mantra'])), name='bhakti_assets_kind_check'),
        ),
    ]
