-- Applied to Supabase via MCP. Forward-only — never edit once applied.
-- Phase 4. Fixes prices generated by 007_consultants.sql.
--
-- 007 derives the 15 and 30 minute bands from the 20 minute price by exact
-- ratio, which is arithmetically right and commercially wrong: ₹1,499 for 20
-- minutes makes 30 minutes ₹2,248.50, and the consultant's own screen duly
-- printed "₹2,248.5". A platform that sets bands does not set that one.
--
-- A separate migration rather than an edit to 007, which has run. Every
-- statement is written as a correction of whatever is there, so replaying the
-- whole folder from nothing lands on the same numbers.
--
-- **The 20-minute price is restored, not rounded.** ₹749, ₹899, ₹1,299 and
-- ₹1,499 are the prices 01-PRD.md §4.1 names, and rounding them to ₹750 and
-- ₹1,500 quietly discards a pricing decision that was already made. Only the
-- derived lengths get rounded:
--
--   20 minutes → exactly what the PRD says
--   15 and 30  → nearest ₹10
--   per minute → nearest ₹1
--
-- `consultant_services` carries a copy of the band price and the RLS policy on
-- it compares the two, so moving one without the other would leave every
-- existing consultant unable to save their own price list. Both move here.

update public.price_bands b
   set price_paise = v.rupees * 100
  from (values (1, 749), (2, 899), (3, 999), (4, 1299), (5, 1499), (6, 2200))
         as v(tier, rupees)
 where b.tier = v.tier
   and b.billing = 'fixed'
   and b.duration_mins = 20
   and b.price_paise <> v.rupees * 100;

update public.price_bands
   set price_paise = round(price_paise / 1000.0) * 1000
 where billing = 'fixed'
   and duration_mins <> 20
   and price_paise <> round(price_paise / 1000.0) * 1000;

update public.price_bands
   set price_paise = round(price_paise / 100.0) * 100
 where billing = 'per_minute'
   and price_paise <> round(price_paise / 100.0) * 100;

update public.consultant_services s
   set price_paise = b.price_paise
  from public.price_bands b
 where b.id = s.band_id
   and s.price_paise <> b.price_paise;

-- Bookings are NOT touched. `bookings.amount_paise` is a frozen copy, and a
-- past booking does not move because the catalogue did.
