# Generated by Django 5.1.15 on 2026-09-19 16:22
# -- FAKE IN AT CUTOVER -- DO NOT RUN FOR REAL ON THE PRODUCTION DATABASE ----
# This migration records Django's ownership of tables that ALREADY EXIST.
# wallets and ledger (003_wallets_ledger.sql, refuse_mutation fixed by 004,
# wallet_debit's client ref_type removed by 005, the refund-per-order index
# added by 013) and payments (006_payments.sql) were created by the numbered
# SQL files; every constraint and index name below is the name Postgres
# already carries, nothing here creates anything new on the real database.
# At cutover: deploy the API against the existing database, then
# `manage.py migrate --fake-initial` (falls back to `--fake wallet` if
# inspectdb-level drift makes --fake-initial refuse). It runs for real only
# on fresh databases (tests, dev scratches).
#
# Cross-module notes: profile_id is a bare UUIDField — the FK to `profiles`
# is deferred to the profile module (9); orders/order_items stay module 6's
# raw-gateway tables. Prod's triggers on wallets/ledger (003's
# refuse_mutation, apply_ledger_to_balance, handle_new_user's wallet
# insert) REMAIN IN FORCE after the fake-in — Django's services replicate
# their behaviour in code only where SQLite has no triggers (the balance
# carry), and never double-write what a prod trigger already does.
# -----------------------------------------------------------------------------

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField()),
                ('provider', models.TextField(default='razorpay')),
                ('provider_order_id', models.TextField(blank=True, null=True)),
                ('provider_payment_id', models.TextField(blank=True, null=True, unique=True)),
                ('provider_event_id', models.TextField(blank=True, null=True, unique=True)),
                ('amount_paise', models.IntegerField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=16)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['profile_id', '-created_at'], name='payments_profile_created_idx'), models.Index(fields=['provider_order_id'], name='payments_order_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['created', 'captured', 'failed', 'refunded'])), name='payments_status_check')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('profile_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('balance_paise', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'wallets',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance_paise__gte', 0)), name='wallets_never_negative')],
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delta_paise', models.IntegerField()),
                ('kind', models.TextField()),
                ('ref_type', models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=16)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('wallet', models.ForeignKey(db_column='wallet_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='wallet.wallet')),
            ],
            options={
                'db_table': 'ledger',
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='ledger_wallet_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('delta_paise', 0), _negated=True), name='ledger_delta_nonzero'), models.CheckConstraint(condition=models.Q(('ref_type__in', ['order', 'payment', 'refund', 'adjustment'])), name='ledger_ref_type_check'), models.UniqueConstraint(condition=models.Q(('ref_id__isnull', False), ('ref_type', 'refund')), fields=('ref_id',), name='ledger_one_refund_per_order')],
            },
        ),
    ]
