# Generated by Django 5.1.15 on 2026-09-30 18:04

import django.utils.timezone
import uuid
from django.db import migrations, models


def lock_out_postgrest(apps, schema_editor):
    """RLS on, no policies. Supabase's PostgREST exposes every table in
    `public` to the anon key, and a table that says who has paid for what
    must not be writable from the browser. Django connects as the owner and
    is unaffected. Postgres only — the test database is SQLite."""
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("alter table entitlements enable row level security")


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField()),
                ('sku', models.CharField(choices=[('ebook', 'E-book'), ('muhurat', 'Muhurat'), ('prediction', 'Prediction')], max_length=16)),
                ('ref', models.TextField(blank=True, default='')),
                ('price_paise', models.IntegerField()),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'entitlements',
                'indexes': [models.Index(fields=['profile_id', 'sku', 'ref'], name='entitlements_lookup_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sku__in', ['ebook', 'muhurat', 'prediction'])), name='entitlements_sku_check'), models.CheckConstraint(condition=models.Q(('price_paise__gt', 0)), name='entitlements_price_positive'), models.UniqueConstraint(condition=models.Q(('expires_at__isnull', True)), fields=('profile_id', 'sku', 'ref'), name='entitlements_once_forever')],
            },
        ),
        migrations.RunPython(lock_out_postgrest, migrations.RunPython.noop),
    ]
