# Generated by Django 5.1.15 on 2026-09-19 09:05
#
# ── FAKE IN AT CUTOVER — DO NOT RUN FOR REAL ON THE PRODUCTION DATABASE ──────
# This migration records Django's ownership of a table that ALREADY EXISTS.
# `reactions` was created by backend/schema/020_content_reviews.sql and
# amended by 025_seekers_publish.sql (which added 'profile' to target_type);
# every constraint and index name below is the name Postgres already carries,
# nothing here creates anything new. At cutover: deploy the API against the
# existing database, then `manage.py migrate --fake-initial` (falls back to
# `--fake reactions` if inspectdb-level drift makes --fake-initial refuse).
# It runs for real only on fresh databases (tests, dev scratches).
# ─────────────────────────────────────────────────────────────────────────────

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField()),
                ('target_type', models.CharField(choices=[('consultant', 'Consultant'), ('content', 'Content'), ('product', 'Product'), ('course', 'Course'), ('live_session', 'Live session'), ('profile', 'Profile')], max_length=16)),
                ('target_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('follow', 'Follow'), ('save', 'Save'), ('like', 'Like'), ('remind', 'Remind')], max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reactions',
                'indexes': [models.Index(fields=['target_type', 'target_id', 'kind'], name='reactions_target_idx')],
                'constraints': [models.UniqueConstraint(fields=('actor_id', 'target_type', 'target_id', 'kind'), name='reactions_actor_id_target_type_target_id_kind_key'), models.CheckConstraint(condition=models.Q(('target_type__in', ['consultant', 'content', 'product', 'course', 'live_session', 'profile'])), name='reactions_target_type_check'), models.CheckConstraint(condition=models.Q(('kind__in', ['follow', 'save', 'like', 'remind'])), name='reactions_kind_check')],
            },
        ),
    ]
