# Generated by Django 5.1.15 on 2026-09-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reaction',
            name='reactions_kind_check',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='kind',
            field=models.CharField(choices=[('follow', 'Follow'), ('save', 'Save'), ('like', 'Like'), ('remind', 'Remind'), ('repost', 'Repost')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['follow', 'save', 'like', 'remind', 'repost'])), name='reactions_kind_check'),
        ),
    ]
