# Generated by Django 5.1.15 on 2026-09-19 08:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=64)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=2048)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_idempotencykey',
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='core_idempo_user_id_aa987a_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'user_id'), name='core_idem_key_user_uniq')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'outbox_events',
                'indexes': [models.Index(fields=['available_at', 'dispatched_at'], name='outbox_even_availab_8f5a4f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(models.Q(('dedupe_key', ''), _negated=True), ('dedupe_key__isnull', False)), fields=('dedupe_key',), name='core_outbox_dedupe_uniq'), models.CheckConstraint(condition=models.Q(('attempts__gte', 0)), name='core_outbox_attempts_nonneg')],
            },
        ),
    ]
