# Generated by Django 5.1.15 on 2026-09-19 14:42
# -- FAKE IN AT CUTOVER -- DO NOT RUN FOR REAL ON THE PRODUCTION DATABASE ----
# This migration records Django's ownership of tables that ALREADY EXIST.
# sessions, threads and messages were created by
# backend/schema/014_metered_chat.sql as amended by 017_no_hold_cap.sql and
# 018_session_review_fixes.sql; every constraint and index name below is the
# name Postgres already carries, nothing here creates anything new on the
# real database. At cutover: deploy the API against the existing database,
# then `manage.py migrate --fake-initial` (falls back to `--fake chat` if
# inspectdb-level drift makes --fake-initial refuse). It runs for real only
# on fresh databases (tests, dev scratches).
#
# Cross-module notes: seeker_id/sender_id are bare UUIDFields — the FKs to
# `profiles` are deferred to the profile module (9); orders stays a raw
# UUIDField owned by the wallet module (8); consultant_id/service_id FK the
# consultants module's real tables (6), and thread_id's FK constraint name
# differs cosmetically from 014's ALTER TABLE sessions_thread_fkey, which
# --fake-initial does not check. Two prod behaviours stay live outside this
# schema and are emulated in the service layer on SQLite: 016's
# touch_thread trigger (threads.last_message_at / last_preview) and the
# phase-2 wallet balance trigger (via apps.consultants.gateway).
# -----------------------------------------------------------------------------

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seeker_id', models.UUIDField()),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_preview', models.TextField(blank=True, null=True)),
                ('legacy_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consultant', models.ForeignKey(db_column='consultant_id', on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='consultants.consultant')),
            ],
            options={
                'db_table': 'threads',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seeker_id', models.UUIDField()),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('chat', 'Chat'), ('call', 'Call'), ('live', 'Live')], max_length=16)),
                ('rate_paise', models.IntegerField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('live', 'Live'), ('ended', 'Ended'), ('declined', 'Declined'), ('expired', 'Expired')], default='requested', max_length=16)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('hold_paise', models.IntegerField(blank=True, null=True)),
                ('charged_paise', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consultant', models.ForeignKey(db_column='consultant_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='consultants.consultant')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='consultants.consultantservice')),
                ('thread', models.ForeignKey(blank=True, db_column='thread_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='chat.thread')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_id', models.UUIDField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.thread')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['consultant_id', '-last_message_at'], name='threads_consultant_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['seeker_id', '-last_message_at'], name='threads_seeker_idx'),
        ),
        migrations.AddConstraint(
            model_name='thread',
            constraint=models.UniqueConstraint(fields=('seeker_id', 'consultant_id'), name='threads_seeker_id_consultant_id_key'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['seeker_id', '-requested_at'], name='sessions_seeker_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['consultant_id', '-requested_at'], name='sessions_consultant_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(condition=models.Q(('status', 'live')), fields=['expires_at'], name='sessions_live_idx'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['chat', 'call', 'live'])), name='sessions_mode_check'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['requested', 'live', 'ended', 'declined', 'expired'])), name='sessions_status_check'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('rate_paise__gt', 0)), name='sessions_rate_paise_check'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'live')), fields=('consultant_id',), name='sessions_one_live_per_consultant'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'requested')), fields=('seeker_id', 'consultant_id'), name='sessions_one_open_request'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread_id', '-created_at'], name='messages_thread_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(condition=models.Q(('read_at__isnull', True)), fields=['thread_id'], name='messages_unread_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='messages_body_check'),
        ),
    ]
