# Generated by Django 5.1.15 on 2026-10-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='audio_only',
            field=models.BooleanField(default=False),
        ),
    ]
