# Generated by Django 5.1.15 on 2026-09-19 10:50
# -- FAKE IN AT CUTOVER -- DO NOT RUN FOR REAL ON THE PRODUCTION DATABASE ----
# This migration records Django's ownership of tables that ALREADY EXIST.
# price_bands, consultants, consultant_services, consultant_availability,
# consultant_time_off (007_consultants.sql, prices corrected by 011),
# bookings (008_bookings.sql, order_id layer from 012) and earnings_ledger
# (012_bookings_transaction.sql) were created by the numbered SQL files;
# every constraint and index name below is the name Postgres already carries
# (the one 64-char unique key is Postgres's own 63-byte truncation),
# nothing here creates anything new on the real database. At cutover: deploy
# the API against the existing database, then
# `manage.py migrate --fake-initial` (falls back to `--fake consultants` if
# inspectdb-level drift makes --fake-initial refuse). It runs for real only
# on fresh databases (tests, dev scratches).
#
# Cross-module notes: profile_id/seeker_id are bare UUIDFields -- the FKs to
# `profiles` are deferred to the profile module; orders/order_id and the
# seeker's ledger/wallets stay raw-gateway tables owned by the wallet module
# (8) until that cutover, and prod's triggers on them remain in force.
# -----------------------------------------------------------------------------
import apps.consultants.fields
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('profile_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('specialization', models.TextField(blank=True, null=True)),
                ('languages', apps.consultants.fields.TextArrayField()),
                ('experience_yrs', models.SmallIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('credentials', apps.consultants.fields.TextArrayField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='pending', max_length=16)),
                ('verified', models.BooleanField(default=False)),
                ('rating_avg_cache', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('rating_count_cache', models.IntegerField(default=0)),
                ('rank_score_cache', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('legacy_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'consultants',
                'indexes': [models.Index(fields=['status'], name='consultants_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'blocked'])), name='consultants_status_check')],
            },
        ),
        migrations.CreateModel(
            name='ConsultantService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('band_id', models.UUIDField()),
                ('mode', models.CharField(choices=[('call', 'Call'), ('chat', 'Chat'), ('live', 'Live'), ('booking', 'Booking')], max_length=16)),
                ('billing', models.CharField(choices=[('fixed', 'Fixed'), ('per_minute', 'Per minute')], default='fixed', max_length=16)),
                ('duration_mins', models.SmallIntegerField()),
                ('price_paise', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('sort', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consultant', models.ForeignKey(db_column='consultant_id', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='consultants.consultant')),
            ],
            options={
                'db_table': 'consultant_services',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seeker_id', models.UUIDField()),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('starts_at', models.DateTimeField()),
                ('duration_mins', models.SmallIntegerField()),
                ('amount_paise', models.IntegerField()),
                ('mode', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No show')], default='pending', max_length=16)),
                ('note', models.TextField(blank=True, null=True)),
                ('legacy_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rescheduled_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultants.booking')),
                ('consultant', models.ForeignKey(db_column='consultant_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='consultants.consultant')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='consultants.consultantservice')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='ConsultantTimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('consultant', models.ForeignKey(db_column='consultant_id', on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='consultants.consultant')),
            ],
            options={
                'db_table': 'consultant_time_off',
            },
        ),
        migrations.CreateModel(
            name='EarningsLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_paise', models.IntegerField()),
                ('fee_bps', models.SmallIntegerField()),
                ('fee_paise', models.IntegerField()),
                ('net_paise', models.IntegerField()),
                ('kind', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultants.booking')),
                ('consultant', models.ForeignKey(db_column='consultant_id', on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='consultants.consultant')),
            ],
            options={
                'db_table': 'earnings_ledger',
            },
        ),
        migrations.CreateModel(
            name='PriceBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.SmallIntegerField()),
                ('billing', models.CharField(choices=[('fixed', 'Fixed'), ('per_minute', 'Per minute')], max_length=16)),
                ('duration_mins', models.SmallIntegerField()),
                ('price_paise', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('sort', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'price_bands',
                'constraints': [models.CheckConstraint(condition=models.Q(('billing__in', ['fixed', 'per_minute'])), name='price_bands_billing_check'), models.CheckConstraint(condition=models.Q(('duration_mins__gt', 0)), name='price_bands_duration_mins_check'), models.CheckConstraint(condition=models.Q(('price_paise__gte', 0)), name='price_bands_price_paise_check'), models.UniqueConstraint(fields=('tier', 'billing', 'duration_mins'), name='price_bands_tier_billing_duration_mins_key')],
            },
        ),
        migrations.CreateModel(
            name='ConsultantAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.SmallIntegerField()),
                ('slot_time', models.TimeField()),
                ('consultant', models.ForeignKey(db_column='consultant_id', on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='consultants.consultant')),
            ],
            options={
                'db_table': 'consultant_availability',
                'constraints': [models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='consultant_availability_weekday_check')],
            },
        ),
        migrations.AddIndex(
            model_name='consultantservice',
            index=models.Index(condition=models.Q(('active', True)), fields=['consultant_id'], name='consultant_services_consultant_idx'),
        ),
        migrations.AddConstraint(
            model_name='consultantservice',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['call', 'chat', 'live', 'booking'])), name='consultant_services_mode_check'),
        ),
        migrations.AddConstraint(
            model_name='consultantservice',
            constraint=models.CheckConstraint(condition=models.Q(('billing__in', ['fixed', 'per_minute'])), name='consultant_services_billing_check'),
        ),
        migrations.AddConstraint(
            model_name='consultantservice',
            constraint=models.CheckConstraint(condition=models.Q(('price_paise__gte', 0)), name='consultant_services_price_paise_check'),
        ),
        migrations.AddConstraint(
            model_name='consultantservice',
            constraint=models.UniqueConstraint(fields=('consultant_id', 'mode', 'billing', 'duration_mins'), name='consultant_services_consultant_id_mode_billing_duration_mins_ke'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['consultant_id', 'starts_at'], name='bookings_consultant_starts_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['seeker_id', '-starts_at'], name='bookings_seeker_starts_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'completed', 'declined', 'cancelled', 'rescheduled', 'no_show'])), name='bookings_status_check'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'confirmed'))), fields=('consultant_id', 'starts_at'), name='bookings_slot_claim'),
        ),
        migrations.AddIndex(
            model_name='consultanttimeoff',
            index=models.Index(fields=['consultant_id', 'starts_at'], name='consultant_time_off_consultant_idx'),
        ),
        migrations.AddConstraint(
            model_name='consultanttimeoff',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='consultant_time_off_ordered'),
        ),
        migrations.AddIndex(
            model_name='earningsledger',
            index=models.Index(fields=['consultant_id', '-created_at'], name='earnings_ledger_consultant_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='earningsledger',
            constraint=models.CheckConstraint(condition=models.Q(('net_paise', django.db.models.expressions.CombinedExpression(models.F('gross_paise'), '-', models.F('fee_paise')))), name='earnings_ledger_nets'),
        ),
    ]
