# Generated by Django 5.1.15 on 2026-09-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='accepting_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultant',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
