# Generated by Django 5.1.15 on 2026-09-26 19:01

import apps.consultants.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_consultant_accepting_now_consultant_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='degree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='degree_asset_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='tags',
            field=apps.consultants.fields.TextArrayField(),
        ),
    ]
