# Generated by Django 5.1.15 on 2026-10-03 17:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def close_to_postgrest(apps, schema_editor):
    """RLS on, no policies: the table is the API's alone, like every money
    table. Without it the anon key could read it through PostgREST."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("alter table payout_details enable row level security")


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0003_consultant_degree_consultant_degree_asset_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutDetails',
            fields=[
                ('consultant', models.OneToOneField(db_column='consultant_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payout_details', serialize=False, to='consultants.consultant')),
                ('pan_cipher', models.TextField()),
                ('pan_last4', models.CharField(max_length=4)),
                ('pan_name', models.TextField()),
                ('account_holder', models.TextField()),
                ('account_cipher', models.TextField()),
                ('account_last4', models.CharField(max_length=4)),
                ('ifsc', models.CharField(max_length=11)),
                ('upi_id', models.TextField(blank=True, default='')),
                ('pan_doc_asset_id', models.UUIDField(blank=True, null=True)),
                ('bank_doc_asset_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted — waiting for a check'), ('verified', 'Verified'), ('rejected', 'Rejected — consultant must fix')], default='submitted', max_length=16)),
                ('review_note', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'payout details',
                'verbose_name_plural': 'payout details',
                'db_table': 'payout_details',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['submitted', 'verified', 'rejected'])), name='payout_details_status_valid')],
            },
        ),
        migrations.RunPython(close_to_postgrest, migrations.RunPython.noop),
    ]
