# Generated by Django 5.1.15 on 2026-09-22 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('profile_id', models.UUIDField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('organic', 'Came on their own'), ('referral', 'Invited by somebody'), ('campaign', 'Tagged link'), ('unknown', 'Arrived before this was recorded')], default='organic', max_length=16)),
                ('referrer_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('campaign', models.CharField(blank=True, default='', max_length=64)),
                ('landed_on', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'attribution',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('visit_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('path', models.CharField(blank=True, default='', max_length=160)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('platform', models.CharField(blank=True, default='', max_length=16)),
                ('app', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'events',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['name', '-created_at'], name='events_name_time_idx'), models.Index(fields=['visit_id', 'created_at'], name='events_visit_idx')],
            },
        ),
    ]
