# Generated by Django 5.1.15 on 2026-09-24 18:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_coupons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('signup', 'Seeker brought a seeker'), ('purchase', "Consultant's code used on a first order")], max_length=16)),
                ('referrer_id', models.UUIDField()),
                ('referee_id', models.UUIDField()),
                ('code', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='shop.order')),
            ],
            options={
                'db_table': 'referrals',
            },
        ),
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField()),
                ('side', models.CharField(choices=[('buyer', 'The buyer'), ('referrer', 'The consultant whose code it was')], max_length=16)),
                ('amount_paise', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending — waiting out the return window'), ('paid', 'Paid'), ('cancelled', 'Cancelled — the order came back')], default='pending', max_length=16)),
                ('matures_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbacks', to='referrals.referral')),
            ],
            options={
                'db_table': 'referral_cashback',
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('seeker', 'Seeker — N'), ('consultant', 'Consultant — A')], max_length=16)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'referral_codes',
                'constraints': [models.UniqueConstraint(fields=('profile_id', 'kind'), name='referral_codes_one_per_kind'), models.CheckConstraint(condition=models.Q(('kind__in', ['seeker', 'consultant'])), name='referral_codes_kind_check')],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer_id', '-created_at'], name='referrals_referrer_idx'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('referee_id', 'kind'), name='referrals_one_per_referee_kind'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('referrer_id', models.F('referee_id')), _negated=True), name='referrals_not_self_check'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['signup', 'purchase'])), name='referrals_kind_check'),
        ),
        migrations.AddIndex(
            model_name='cashback',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['matures_at'], name='cashback_due_idx'),
        ),
        migrations.AddIndex(
            model_name='cashback',
            index=models.Index(fields=['profile_id', '-created_at'], name='cashback_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashback',
            constraint=models.UniqueConstraint(fields=('referral', 'side'), name='cashback_one_per_side'),
        ),
        migrations.AddConstraint(
            model_name='cashback',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='cashback_amount_positive'),
        ),
    ]
