# Generated by Django 5.1.15 on 2026-09-24 18:29

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField()),
                ('kind', models.CharField(max_length=64)),
                ('title', models.TextField()),
                ('body', models.TextField(blank=True, null=True)),
                ('ref_type', models.CharField(blank=True, max_length=32, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=64, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['profile_id', '-created_at'], name='notif_owner_idx'), models.Index(condition=models.Q(('read_at__isnull', True)), fields=['profile_id'], name='notif_unread_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False)), fields=('dedupe_key',), name='notifications_dedupe_uniq')],
            },
        ),
    ]
